language: java
sudo: false

jdk:
  - oraclejdk8

os:
  - linux

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd AntiSpamWekaCLI

script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
